--------------------------------------------------------
--  File created - miércoles-mayo-22-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CLIENTES
--------------------------------------------------------

  CREATE TABLE "STORAGE"."CLIENTES" 
   (	"ID_CLIENTE" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ID_USUARIO" NUMBER(*,0), 
	"DOCUMENTO" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table OPERADORES
--------------------------------------------------------

  CREATE TABLE "STORAGE"."OPERADORES" 
   (	"ID_OPERADOR" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ID_USUARIO" NUMBER(*,0), 
	"CARGO" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ORDENES
--------------------------------------------------------

  CREATE TABLE "STORAGE"."ORDENES" 
   (	"ID_ORDEN" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"ID_CLIENTE" NUMBER(*,0), 
	"IMPORTE" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ORDENES_OPERADORES
--------------------------------------------------------

  CREATE TABLE "STORAGE"."ORDENES_OPERADORES" 
   (	"ID_OPERADOR" NUMBER(*,0), 
	"ID_ORDEN" NUMBER(*,0), 
	"FECHA" TIMESTAMP (6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ORDENES_PRODUCTOS
--------------------------------------------------------

  CREATE TABLE "STORAGE"."ORDENES_PRODUCTOS" 
   (	"ID_ORDEN" NUMBER(*,0), 
	"ID_PRODUCTO" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODUCTOS
--------------------------------------------------------

  CREATE TABLE "STORAGE"."PRODUCTOS" 
   (	"ID_PRODUCTO" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"TIPO" VARCHAR2(50 BYTE), 
	"CODIGO" VARCHAR2(100 BYTE), 
	"PRECIO" NUMBER(20,2), 
	"STOCK" NUMBER(*,0), 
	"IMG" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USUARIOS
--------------------------------------------------------

  CREATE TABLE "STORAGE"."USUARIOS" 
   (	"ID_USUARIO" NUMBER(*,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"APELLIDO" VARCHAR2(100 BYTE), 
	"TELEFONO" NUMBER(*,0), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"USUARIO" VARCHAR2(100 BYTE), 
	"CONTRASENIA" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into STORAGE.CLIENTES
SET DEFINE OFF;
Insert into STORAGE.CLIENTES (ID_CLIENTE,ID_USUARIO,DOCUMENTO) values (22,43,'111222333444');
Insert into STORAGE.CLIENTES (ID_CLIENTE,ID_USUARIO,DOCUMENTO) values (14,29,'21812925010');
Insert into STORAGE.CLIENTES (ID_CLIENTE,ID_USUARIO,DOCUMENTO) values (41,62,'11119999333');
Insert into STORAGE.CLIENTES (ID_CLIENTE,ID_USUARIO,DOCUMENTO) values (42,64,'3580235454');
REM INSERTING into STORAGE.OPERADORES
SET DEFINE OFF;
Insert into STORAGE.OPERADORES (ID_OPERADOR,ID_USUARIO,CARGO) values (21,41,'Ventas');
Insert into STORAGE.OPERADORES (ID_OPERADOR,ID_USUARIO,CARGO) values (1,31,'JEFE');
Insert into STORAGE.OPERADORES (ID_OPERADOR,ID_USUARIO,CARGO) values (41,61,'Ventas');
Insert into STORAGE.OPERADORES (ID_OPERADOR,ID_USUARIO,CARGO) values (42,63,'Ventas');
REM INSERTING into STORAGE.ORDENES
SET DEFINE OFF;
REM INSERTING into STORAGE.ORDENES_OPERADORES
SET DEFINE OFF;
REM INSERTING into STORAGE.ORDENES_PRODUCTOS
SET DEFINE OFF;
REM INSERTING into STORAGE.PRODUCTOS
SET DEFINE OFF;
Insert into STORAGE.PRODUCTOS (ID_PRODUCTO,NOMBRE,TIPO,CODIGO,PRECIO,STOCK,IMG) values (21,'1PLZ','Gavetas','1234',100,10,null);
Insert into STORAGE.PRODUCTOS (ID_PRODUCTO,NOMBRE,TIPO,CODIGO,PRECIO,STOCK,IMG) values (45,'Armario Metalico','Armario','12352135',600,100,null);
Insert into STORAGE.PRODUCTOS (ID_PRODUCTO,NOMBRE,TIPO,CODIGO,PRECIO,STOCK,IMG) values (43,'Caja Athena','Caja plastica','9999',200,10,null);
Insert into STORAGE.PRODUCTOS (ID_PRODUCTO,NOMBRE,TIPO,CODIGO,PRECIO,STOCK,IMG) values (44,'4PLZ','Gavetas','12353',230,1000,null);
REM INSERTING into STORAGE.USUARIOS
SET DEFINE OFF;
Insert into STORAGE.USUARIOS (ID_USUARIO,NOMBRE,APELLIDO,TELEFONO,EMAIL,USUARIO,CONTRASENIA) values (41,'Pedro','Martinez',97151243,'pmartinez@gmail.com','pedro.martinez','Pedro1234.');
Insert into STORAGE.USUARIOS (ID_USUARIO,NOMBRE,APELLIDO,TELEFONO,EMAIL,USUARIO,CONTRASENIA) values (43,'Juan','Perez',97123457,'jperez@gmail.com','juan.perez','Perez1234.');
Insert into STORAGE.USUARIOS (ID_USUARIO,NOMBRE,APELLIDO,TELEFONO,EMAIL,USUARIO,CONTRASENIA) values (31,'Diego','Battistin',97571439,'diego@gmail.com','Diego_Battistin','Diego1234.');
Insert into STORAGE.USUARIOS (ID_USUARIO,NOMBRE,APELLIDO,TELEFONO,EMAIL,USUARIO,CONTRASENIA) values (62,'Lucas','Perez',98123754,'lperez@gmail.com','lucas.perez','Ñucas1234.');
Insert into STORAGE.USUARIOS (ID_USUARIO,NOMBRE,APELLIDO,TELEFONO,EMAIL,USUARIO,CONTRASENIA) values (61,'Luis','Gonzalez',95123678,'lgonzalez@gmail.com','luis.gonzalez','Luis1234.');
Insert into STORAGE.USUARIOS (ID_USUARIO,NOMBRE,APELLIDO,TELEFONO,EMAIL,USUARIO,CONTRASENIA) values (63,'Fernando','Alonso',97123543,'falonso@gmail.com','fernando.alonoso','Fernando1234.');
Insert into STORAGE.USUARIOS (ID_USUARIO,NOMBRE,APELLIDO,TELEFONO,EMAIL,USUARIO,CONTRASENIA) values (64,'Carlos','Sainz',97325123,'csainz@gmail.com','carlos.sainz','Carlos1234.');
Insert into STORAGE.USUARIOS (ID_USUARIO,NOMBRE,APELLIDO,TELEFONO,EMAIL,USUARIO,CONTRASENIA) values (29,'Gianluca','Battistin',97571439,'gian@gmail.com','Gianluca_Battistin','Gian1234.');
--------------------------------------------------------
--  DDL for Index PK_ID_CLIENTE
--------------------------------------------------------

  CREATE UNIQUE INDEX "STORAGE"."PK_ID_CLIENTE" ON "STORAGE"."CLIENTES" ("ID_CLIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ID_OPERADOR
--------------------------------------------------------

  CREATE UNIQUE INDEX "STORAGE"."PK_ID_OPERADOR" ON "STORAGE"."OPERADORES" ("ID_OPERADOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ID_ORDEN
--------------------------------------------------------

  CREATE UNIQUE INDEX "STORAGE"."PK_ID_ORDEN" ON "STORAGE"."ORDENES" ("ID_ORDEN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ID_PRODUCTO
--------------------------------------------------------

  CREATE UNIQUE INDEX "STORAGE"."PK_ID_PRODUCTO" ON "STORAGE"."PRODUCTOS" ("ID_PRODUCTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ID_USUARIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "STORAGE"."PK_ID_USUARIO" ON "STORAGE"."USUARIOS" ("ID_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ORDENES_PRODUTOS
--------------------------------------------------------

  CREATE UNIQUE INDEX "STORAGE"."PK_ORDENES_PRODUTOS" ON "STORAGE"."ORDENES_PRODUCTOS" ("ID_ORDEN", "ID_PRODUCTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ORDEN_OPERADOR
--------------------------------------------------------

  CREATE UNIQUE INDEX "STORAGE"."PK_ORDEN_OPERADOR" ON "STORAGE"."ORDENES_OPERADORES" ("ID_OPERADOR", "ID_ORDEN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_CODIGO
--------------------------------------------------------

  CREATE UNIQUE INDEX "STORAGE"."UK_CODIGO" ON "STORAGE"."PRODUCTOS" ("CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_EMAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "STORAGE"."UK_EMAIL" ON "STORAGE"."USUARIOS" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_USUARIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "STORAGE"."UK_USUARIO" ON "STORAGE"."USUARIOS" ("USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ID_CLIENTE
--------------------------------------------------------

  CREATE UNIQUE INDEX "STORAGE"."PK_ID_CLIENTE" ON "STORAGE"."CLIENTES" ("ID_CLIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ID_OPERADOR
--------------------------------------------------------

  CREATE UNIQUE INDEX "STORAGE"."PK_ID_OPERADOR" ON "STORAGE"."OPERADORES" ("ID_OPERADOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ID_ORDEN
--------------------------------------------------------

  CREATE UNIQUE INDEX "STORAGE"."PK_ID_ORDEN" ON "STORAGE"."ORDENES" ("ID_ORDEN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ORDEN_OPERADOR
--------------------------------------------------------

  CREATE UNIQUE INDEX "STORAGE"."PK_ORDEN_OPERADOR" ON "STORAGE"."ORDENES_OPERADORES" ("ID_OPERADOR", "ID_ORDEN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ORDENES_PRODUTOS
--------------------------------------------------------

  CREATE UNIQUE INDEX "STORAGE"."PK_ORDENES_PRODUTOS" ON "STORAGE"."ORDENES_PRODUCTOS" ("ID_ORDEN", "ID_PRODUCTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ID_PRODUCTO
--------------------------------------------------------

  CREATE UNIQUE INDEX "STORAGE"."PK_ID_PRODUCTO" ON "STORAGE"."PRODUCTOS" ("ID_PRODUCTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_CODIGO
--------------------------------------------------------

  CREATE UNIQUE INDEX "STORAGE"."UK_CODIGO" ON "STORAGE"."PRODUCTOS" ("CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ID_USUARIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "STORAGE"."PK_ID_USUARIO" ON "STORAGE"."USUARIOS" ("ID_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_USUARIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "STORAGE"."UK_USUARIO" ON "STORAGE"."USUARIOS" ("USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_EMAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "STORAGE"."UK_EMAIL" ON "STORAGE"."USUARIOS" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CLIENTES
--------------------------------------------------------

  ALTER TABLE "STORAGE"."CLIENTES" MODIFY ("ID_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "STORAGE"."CLIENTES" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "STORAGE"."CLIENTES" ADD CONSTRAINT "PK_ID_CLIENTE" PRIMARY KEY ("ID_CLIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table OPERADORES
--------------------------------------------------------

  ALTER TABLE "STORAGE"."OPERADORES" MODIFY ("ID_OPERADOR" NOT NULL ENABLE);
  ALTER TABLE "STORAGE"."OPERADORES" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "STORAGE"."OPERADORES" ADD CONSTRAINT "PK_ID_OPERADOR" PRIMARY KEY ("ID_OPERADOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ORDENES
--------------------------------------------------------

  ALTER TABLE "STORAGE"."ORDENES" MODIFY ("ID_ORDEN" NOT NULL ENABLE);
  ALTER TABLE "STORAGE"."ORDENES" MODIFY ("ID_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "STORAGE"."ORDENES" ADD CONSTRAINT "PK_ID_ORDEN" PRIMARY KEY ("ID_ORDEN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ORDENES_OPERADORES
--------------------------------------------------------

  ALTER TABLE "STORAGE"."ORDENES_OPERADORES" MODIFY ("ID_OPERADOR" NOT NULL ENABLE);
  ALTER TABLE "STORAGE"."ORDENES_OPERADORES" MODIFY ("ID_ORDEN" NOT NULL ENABLE);
  ALTER TABLE "STORAGE"."ORDENES_OPERADORES" MODIFY ("FECHA" NOT NULL ENABLE);
  ALTER TABLE "STORAGE"."ORDENES_OPERADORES" ADD CONSTRAINT "PK_ORDEN_OPERADOR" PRIMARY KEY ("ID_OPERADOR", "ID_ORDEN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ORDENES_PRODUCTOS
--------------------------------------------------------

  ALTER TABLE "STORAGE"."ORDENES_PRODUCTOS" MODIFY ("ID_ORDEN" NOT NULL ENABLE);
  ALTER TABLE "STORAGE"."ORDENES_PRODUCTOS" MODIFY ("ID_PRODUCTO" NOT NULL ENABLE);
  ALTER TABLE "STORAGE"."ORDENES_PRODUCTOS" ADD CONSTRAINT "PK_ORDENES_PRODUTOS" PRIMARY KEY ("ID_ORDEN", "ID_PRODUCTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCTOS
--------------------------------------------------------

  ALTER TABLE "STORAGE"."PRODUCTOS" MODIFY ("ID_PRODUCTO" NOT NULL ENABLE);
  ALTER TABLE "STORAGE"."PRODUCTOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "STORAGE"."PRODUCTOS" MODIFY ("TIPO" NOT NULL ENABLE);
  ALTER TABLE "STORAGE"."PRODUCTOS" ADD CONSTRAINT "PK_ID_PRODUCTO" PRIMARY KEY ("ID_PRODUCTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "STORAGE"."PRODUCTOS" ADD CONSTRAINT "UK_CODIGO" UNIQUE ("CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USUARIOS
--------------------------------------------------------

  ALTER TABLE "STORAGE"."USUARIOS" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "STORAGE"."USUARIOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "STORAGE"."USUARIOS" MODIFY ("APELLIDO" NOT NULL ENABLE);
  ALTER TABLE "STORAGE"."USUARIOS" MODIFY ("TELEFONO" NOT NULL ENABLE);
  ALTER TABLE "STORAGE"."USUARIOS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "STORAGE"."USUARIOS" MODIFY ("USUARIO" NOT NULL ENABLE);
  ALTER TABLE "STORAGE"."USUARIOS" MODIFY ("CONTRASENIA" NOT NULL ENABLE);
  ALTER TABLE "STORAGE"."USUARIOS" ADD CONSTRAINT "PK_ID_USUARIO" PRIMARY KEY ("ID_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "STORAGE"."USUARIOS" ADD CONSTRAINT "UK_USUARIO" UNIQUE ("USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "STORAGE"."USUARIOS" ADD CONSTRAINT "UK_EMAIL" UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CLIENTES
--------------------------------------------------------

  ALTER TABLE "STORAGE"."CLIENTES" ADD CONSTRAINT "FK_CLIENTE_OPERADOR" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "STORAGE"."USUARIOS" ("ID_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table OPERADORES
--------------------------------------------------------

  ALTER TABLE "STORAGE"."OPERADORES" ADD CONSTRAINT "FK_OPERADOR_USUARIO" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "STORAGE"."USUARIOS" ("ID_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORDENES
--------------------------------------------------------

  ALTER TABLE "STORAGE"."ORDENES" ADD CONSTRAINT "FK_CLIENTE_ORDEN" FOREIGN KEY ("ID_CLIENTE")
	  REFERENCES "STORAGE"."CLIENTES" ("ID_CLIENTE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORDENES_OPERADORES
--------------------------------------------------------

  ALTER TABLE "STORAGE"."ORDENES_OPERADORES" ADD CONSTRAINT "FK_OPERADOR" FOREIGN KEY ("ID_OPERADOR")
	  REFERENCES "STORAGE"."OPERADORES" ("ID_OPERADOR") ENABLE;
  ALTER TABLE "STORAGE"."ORDENES_OPERADORES" ADD CONSTRAINT "FK_ORDEN" FOREIGN KEY ("ID_ORDEN")
	  REFERENCES "STORAGE"."ORDENES" ("ID_ORDEN") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORDENES_PRODUCTOS
--------------------------------------------------------

  ALTER TABLE "STORAGE"."ORDENES_PRODUCTOS" ADD CONSTRAINT "FK_ORD_PROD" FOREIGN KEY ("ID_ORDEN")
	  REFERENCES "STORAGE"."ORDENES" ("ID_ORDEN") ENABLE;
  ALTER TABLE "STORAGE"."ORDENES_PRODUCTOS" ADD CONSTRAINT "FK_PROD_ORD" FOREIGN KEY ("ID_PRODUCTO")
	  REFERENCES "STORAGE"."PRODUCTOS" ("ID_PRODUCTO") ENABLE;
